# coding: utf-8

"""
    Swagger Petstore

    This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.pet_api import PetApi


class TestPetApi(unittest.TestCase):
    """ PetApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.pet_api.PetApi()

    def tearDown(self):
        pass

    def test_add_pet(self):
        """
        Test case for add_pet

        Add a new pet to the store
        """
        pass

    def test_delete_pet(self):
        """
        Test case for delete_pet

        Deletes a pet
        """
        pass

    def test_find_pets_by_status(self):
        """
        Test case for find_pets_by_status

        Finds Pets by status
        """
        pass

    def test_find_pets_by_tags(self):
        """
        Test case for find_pets_by_tags

        Finds Pets by tags
        """
        pass

    def test_get_pet_by_id(self):
        """
        Test case for get_pet_by_id

        Find pet by ID
        """
        pass

    def test_update_pet(self):
        """
        Test case for update_pet

        Update an existing pet
        """
        pass

    def test_update_pet_with_form(self):
        """
        Test case for update_pet_with_form

        Updates a pet in the store with form data
        """
        pass

    def test_upload_file(self):
        """
        Test case for upload_file

        uploads an image
        """
        pass


if __name__ == '__main__':
    unittest.main()
